%% ExportFigures.m
% Generates trajectory plot from CSV and saves all figures as PNG.
% Run this script AFTER running UserMain.m and RunDisturbanceSim.m.
%
% What it does:
%   1. Reads the CSV file generated by RunDisturbanceSim.m
%   2. Creates voltage magnitude trajectory plot with custom settings
%   3. Saves all open figures as PNG files
clc;

%% Configuration
% Use absolute path to ensure correct location
scriptDir  = fileparts(mfilename('fullpath'));
figureDir  = fullfile(scriptDir, 'figures');

% Create figures directory if it doesn't exist
if ~exist(figureDir, 'dir')
    [success, msg] = mkdir(figureDir);
    if ~success
        error('Failed to create directory %s: %s', figureDir, msg);
    end
    fprintf('Created directory: %s\n', figureDir);
end

outputFile = fullfile(figureDir, 'disturbance_sim_results.csv');

%% Read CSV file
if ~isfile(outputFile)
    error('CSV file not found: %s\nPlease run RunDisturbanceSim.m first.', outputFile);
end

fprintf('Reading data from: %s\n', outputFile);
data = readmatrix(outputFile);
fid = fopen(outputFile, 'r');
headerLine = fgetl(fid);
fclose(fid);
headers = strsplit(headerLine, ',');

t = data(:, 1);
t_end = max(t);

%% Create voltage magnitude trajectory plot
fprintf('Creating voltage magnitude trajectory plot...\n');

% Find all bus indices from headers
activeBuses = [];
for i = 1:length(headers)
    if contains(headers{i}, 'v_d_Bus')
        busNum = str2double(regexp(headers{i}, '\d+', 'match'));
        if ~ismember(busNum, activeBuses)
            activeBuses(end+1) = busNum;
        end
    end
end
activeBuses = sort(activeBuses);

% Calculate voltage magnitudes for all buses
v_magnitudes = cell(1, length(activeBuses));
for idx = 1:length(activeBuses)
    k = activeBuses(idx);
    col_d = find(strcmp(headers, ['v_d_Bus' num2str(k)]));
    col_q = find(strcmp(headers, ['v_q_Bus' num2str(k)]));

    if ~isempty(col_d) && ~isempty(col_q)
        v_magnitudes{idx} = sqrt(data(:, col_d).^2 + data(:, col_q).^2);
    end
end

% Create figure with three subplots (stacked vertically)
fig_trajectory = figure('Name', 'Voltage_Trajectory', 'Position', [100, 100, 600, 700]);

% Subplot 1: Full simulation time (0-30s) - Top
subplot(3, 1, 1);
hold on;
for idx = 1:length(activeBuses)
    k = activeBuses(idx);
    if ~isempty(v_magnitudes{idx})
        plot(t, v_magnitudes{idx}, 'LineWidth', 1.5, 'DisplayName', ['Bus ' num2str(k)]);
    end
end
hold off;
ylabel('Voltage Magnitude [p.u.]');
title('Voltage Magnitude (full sim time)');
legend('show', 'Location', 'southeast');
grid on;
xlim([0 t_end]);
ylim([0 1.2]);

% Subplot 2: Short circuit zoomed view (0-0.5s) - Middle
subplot(3, 1, 2);
hold on;
for idx = 1:length(activeBuses)
    k = activeBuses(idx);
    if ~isempty(v_magnitudes{idx})
        plot(t, v_magnitudes{idx}, 'LineWidth', 1.5, 'DisplayName', ['Bus ' num2str(k)]);
    end
end
hold off;
ylabel('Voltage Magnitude [p.u.]');
title('Short Circuit');
grid on;
xlim([0 0.5]);
ylim([0 1.2]);

% Subplot 3: EMT transients after clearing (0.199-0.204s) - Bottom
subplot(3, 1, 3);
hold on;
for idx = 1:length(activeBuses)
    k = activeBuses(idx);
    if ~isempty(v_magnitudes{idx})
        plot(t, v_magnitudes{idx}, 'LineWidth', 1.5, 'DisplayName', ['Bus ' num2str(k)]);
    end
end
hold off;
xlabel('Time [s]');
ylabel('Voltage Magnitude [p.u.]');
title('EMT Transients after fault clearing');
grid on;
xlim([0.199 0.204]);
ylim([0.55 1.65]);

fprintf('Trajectory plot created (3 subplots).\n');

%% Save all open figures
allFigs = findall(0, 'Type', 'figure');
numFigs = length(allFigs);

fprintf('\nFound %d figure(s) to save.\n', numFigs);

for i = 1:numFigs
    figHandle = allFigs(i);

    % Get figure name or use figure number
    figName = get(figHandle, 'Name');
    if isempty(figName)
        figName = sprintf('Figure_%d', get(figHandle, 'Number'));
    else
        % Clean figure name for filename (remove invalid characters)
        figName = regexprep(figName, '[^\w\-]', '_');
    end

    % Construct output filename
    outputPath = fullfile(figureDir, [figName '.png']);

    % Save as PNG with high resolution
    fprintf('  Saving: %s\n', outputPath);
    try
        print(figHandle, outputPath, '-dpng', '-r300');
    catch ME
        warning('Failed to save %s: %s', figName, ME.message);
    end
end

fprintf('\nAll figures saved to: %s\n', fullfile(pwd, figureDir));
fprintf('Workflow complete!\n');
